<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
      <Folder Include="Cli\" />
      <Folder Include="Database\" />
      <Folder Include="Services\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\InfiniLore.Core.Modules.Users.Shared\InfiniLore.Core.Modules.Users.Shared.csproj" />
      <ProjectReference Include="..\InfiniLore.Core.Shared\InfiniLore.Core.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="CodeOfChaos.CliArgsParser" />
      <PackageReference Include="CodeOfChaos.CliArgsParser.Contracts" />
      <PackageReference Include="CodeOfChaos.CliArgsParser.Generators">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

</Project>
