// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace InfiniLore.KiotaApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InfiniLoreServerAPIModelsJwtResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accessToken property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessToken { get; set; }
#nullable restore
#else
        public string AccessToken { get; set; }
#endif
        /// <summary>The accessTokenExpiryUtc property</summary>
        public DateTimeOffset? AccessTokenExpiryUtc { get; set; }
        /// <summary>The refreshToken property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RefreshToken { get; set; }
#nullable restore
#else
        public string RefreshToken { get; set; }
#endif
        /// <summary>The refreshTokenExpiryUtc property</summary>
        public DateTimeOffset? RefreshTokenExpiryUtc { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::InfiniLore.KiotaApiClient.Models.InfiniLoreServerAPIModelsJwtResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::InfiniLore.KiotaApiClient.Models.InfiniLoreServerAPIModelsJwtResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::InfiniLore.KiotaApiClient.Models.InfiniLoreServerAPIModelsJwtResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accessToken", n => { AccessToken = n.GetStringValue(); } },
                { "accessTokenExpiryUtc", n => { AccessTokenExpiryUtc = n.GetDateTimeOffsetValue(); } },
                { "refreshToken", n => { RefreshToken = n.GetStringValue(); } },
                { "refreshTokenExpiryUtc", n => { RefreshTokenExpiryUtc = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accessToken", AccessToken);
            writer.WriteDateTimeOffsetValue("accessTokenExpiryUtc", AccessTokenExpiryUtc);
            writer.WriteStringValue("refreshToken", RefreshToken);
            writer.WriteDateTimeOffsetValue("refreshTokenExpiryUtc", RefreshTokenExpiryUtc);
        }
    }
}
#pragma warning restore CS0618
