<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>        
        <PackageReference Include="CodeOfChaos.Extensions.MicrosoftLogging"  />
        <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection" />
        <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection.Generators" >
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
        
        <PackageReference Include="Serilog" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\InfiniLore.Modules.Core.Shared\InfiniLore.Modules.Core.Shared.csproj" />
      <ProjectReference Include="..\InfiniLore.Shared\InfiniLore.Shared.csproj" />
    </ItemGroup>

</Project>
