<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <RootNamespace>InfiniLore.Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
      <PackageReference Include="CodeOfChaos.CliArgsParser" />
      <PackageReference Include="CodeOfChaos.CliArgsParser.Generators">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection.Generators">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="FastEndpoints" />
      <PackageReference Include="InfiniLore.InfiniBlazor" />
      <PackageReference Include="Microsoft.CodeAnalysis" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Services\Cli\" />
    </ItemGroup>

</Project>
