<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AterraEngine.Unions" />
        <PackageReference Include="Auth0.AuthenticationApi" />
        <PackageReference Include="Auth0.ManagementApi" />
        <PackageReference Include="CodeOfChaos.Extensions" />
        <PackageReference Include="CodeOfChaos.Extensions.AspNetCore" />
        <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection" />
        <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection.Generators" >
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="CodeOfChaos.Extensions.EntityFrameworkCore" />
        <PackageReference Include="CodeOfChaos.Extensions.MicrosoftLogging" />
        <PackageReference Include="CodeOfChaos.Types.UnitOfWork" />
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
        <PackageReference Include="Minio" />
        <PackageReference Include="Testcontainers.Minio" />
        <PackageReference Include="Testcontainers.MsSql" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\InfiniLore.Server.Contracts\InfiniLore.Server.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Migrations\Content\" />
    </ItemGroup>

</Project>
