<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Configurations\Data\User\" />
      <Folder Include="Repositories\Account\" />
      <Folder Include="Repositories\Data\User\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="CodeOfChaos.Extensions.AspNetCore" Version="0.36.4" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
      <PackageReference Include="Testcontainers.MsSql" Version="4.2.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\InfiniLore.Server.Contracts\InfiniLore.Server.Contracts.csproj" />
      <ProjectReference Include="..\InfiniLore.Server.Database.Models\InfiniLore.Server.Database.Models.csproj" />
      <ProjectReference Include="..\server\Old.InfiniLore.Database\Old.InfiniLore.Database.csproj" />
    </ItemGroup>

</Project>
