<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CodeOfChaos.Extensions.AspNetCore" />
        <PackageReference Include="CodeOfChaos.Extensions.EntityFrameworkCore" />
        <PackageReference Include="CodeOfChaos.Extensions.MicrosoftLogging" />
        <PackageReference Include="CodeOfChaos.Types.UnitOfWork" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
        <PackageReference Include="Minio" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Migrations\Content\" />
    </ItemGroup>

</Project>
