// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace InfiniLore.Kiota.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InfiniLoreServerModulesCoreApiEndpointsPaginatedResponseOfLoreScopeResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The currentPage property</summary>
        public int? CurrentPage { get; set; }
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::InfiniLore.Kiota.Models.InfiniLoreServerModulesLoreScopesApiEndpointsLoreScopeResponse>? Items { get; set; }
#nullable restore
#else
        public List<global::InfiniLore.Kiota.Models.InfiniLoreServerModulesLoreScopesApiEndpointsLoreScopeResponse> Items { get; set; }
#endif
        /// <summary>The totalCount property</summary>
        public int? TotalCount { get; set; }
        /// <summary>The totalPages property</summary>
        public int? TotalPages { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::InfiniLore.Kiota.Models.InfiniLoreServerModulesCoreApiEndpointsPaginatedResponseOfLoreScopeResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::InfiniLore.Kiota.Models.InfiniLoreServerModulesCoreApiEndpointsPaginatedResponseOfLoreScopeResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::InfiniLore.Kiota.Models.InfiniLoreServerModulesCoreApiEndpointsPaginatedResponseOfLoreScopeResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currentPage", n => { CurrentPage = n.GetIntValue(); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::InfiniLore.Kiota.Models.InfiniLoreServerModulesLoreScopesApiEndpointsLoreScopeResponse>(global::InfiniLore.Kiota.Models.InfiniLoreServerModulesLoreScopesApiEndpointsLoreScopeResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "totalCount", n => { TotalCount = n.GetIntValue(); } },
                { "totalPages", n => { TotalPages = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("currentPage", CurrentPage);
            writer.WriteCollectionOfObjectValues<global::InfiniLore.Kiota.Models.InfiniLoreServerModulesLoreScopesApiEndpointsLoreScopeResponse>("items", Items);
            writer.WriteIntValue("totalCount", TotalCount);
            writer.WriteIntValue("totalPages", TotalPages);
        }
    }
}
#pragma warning restore CS0618
