<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <IsPackable>true</IsPackable>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>

        <DevelopmentDependency>true</DevelopmentDependency>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>

        <!-- Package metadata -->
        <PackageId>InfiniLore.InfiniBlazor.Theming.Generators</PackageId>
        <Version>0.1.0-preview.23</Version>
        <Authors>Anna Sas</Authors>
        <Description>Generators to help with InfiniBlazor's Theming Library</Description>
        <PackageProjectUrl>https://github.com/InfiniLore/InfiniLore.InfiniBlazor</PackageProjectUrl>
        <PackageTags>Blazor;Ui;Design;Components;Library;Contracts;Generator</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <IncludeSymbols>true</IncludeSymbols>
        <DebugType>embedded</DebugType>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../LICENSE" Pack="true" PackagePath="" Visible="false" />
        <None Include="../../README.md" Pack="true" PackagePath="" Visible="false" />
        <None Include="../../assets/icon.png" Pack="true" PackagePath="" Visible="false" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="IsExternalInit">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.Common" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
        <PackageReference Include="CodeOfChaos.GeneratorTools" Pack="true" GeneratePathProperty="true" PrivateAssets="all" />
        <PackageReference Include="Nullable">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
        <None Include="$(PkgCodeOfChaos_GeneratorTools)\lib\netstandard2.0\*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    </ItemGroup>
    
</Project>
