<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>InfiniLore.Server.Modules.Core</RootNamespace>

        <!-- Package metadata -->
        <PackageId>InfiniLore.InfiniBlazor.Theming</PackageId>
        <Version>0.1.0-preview.23</Version>
        <Authors>Anna Sas</Authors>
        <Description>CSS Theme library for InfiniLore's Component Library</Description>
        <PackageProjectUrl>https://github.com/InfiniLore/InfiniLore.InfiniBlazor</PackageProjectUrl>
        <PackageTags>Blazor;Ui;Design;Components;Library;Contracts</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <IncludeSymbols>true</IncludeSymbols>
        <DebugType>embedded</DebugType>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../LICENSE" Pack="true" PackagePath="" Visible="false" />
        <None Include="../../README.md" Pack="true" PackagePath="" Visible="false" />
        <None Include="../../assets/icon.png" Pack="true" PackagePath="" Visible="false" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\InfiniLore.Server.Contracts\InfiniLore.Server.Contracts.csproj" />
        <ProjectReference Include="..\InfiniLore.Shared.Modules.Core\InfiniLore.Shared.Modules.Core.csproj" />
        <ProjectReference Include="..\InfiniLore.Shared.Contracts\InfiniLore.Shared.Contracts.csproj" /> 
        <ProjectReference Include="..\InfiniLore.Server.SourceGenerators\InfiniLore.Server.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CodeOfChaos.Extensions" />

        <!-- Ugly, but this is because of some weirdness with how analyzers are imported through a project reference -->
        <PackageReference Include="CodeOfChaos.GeneratorTools" GeneratePathProperty="true" PrivateAssets="all" />
        <Analyzer Include="$(PkgCodeOfChaos_GeneratorTools)\lib\netstandard2.0\*.dll" />
        
        <PackageReference Include="CodeOfChaos.Types.UnitOfWork.Contracts" />
        <PackageReference Include="AterraEngine.Unions"/>
        <PackageReference Include="AterraEngine.Unions.Generators">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        
        <PackageReference Include="FastEndpoints" />
        <PackageReference Include="FastEndpoints.Messaging.Core" />
        <PackageReference Include="JetBrains.Annotations" />
    </ItemGroup>

</Project>
