<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
      <PackageReference Include="FastEndpoints.Messaging.Core" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\InfiniLore.Core.Database\InfiniLore.Core.Database.csproj" />
      <ProjectReference Include="..\InfiniLore.Core.Shared\InfiniLore.Core.Shared.csproj" />
    </ItemGroup>

</Project>
