<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <PlatformTarget>x64</PlatformTarget>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <RootNamespace>InfiniLore.Application.Desktop</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="InfiniLore.InfiniBlazor" />
      <PackageReference Include="InfiniLore.InfiniFrame" />
      <PackageReference Include="InfiniLore.InfiniFrame.Blazor" />
      <PackageReference Include="InfiniLore.InfiniFrame.Server" />
      <PackageReference Include="Serilog" />
      <PackageReference Include="Serilog.AspNetCore" />
      <PackageReference Include="Serilog.Sinks.Async" />
      <PackageReference Include="Serilog.Sinks.Console" />
    </ItemGroup>

    <ItemGroup>
        <Content Update="wwwroot\**">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\core\InfiniLore.Core.Modular\InfiniLore.Core.Modular.csproj" />
      <ProjectReference Include="..\..\core\InfiniLore.Core\InfiniLore.Core.csproj" />
      <ProjectReference Include="..\..\modules\InfiniLore.Modules.Assets\InfiniLore.Modules.Assets.csproj" />
      <ProjectReference Include="..\..\modules\InfiniLore.Modules.Projects\InfiniLore.Modules.Projects.csproj" />
      <ProjectReference Include="..\..\modules\InfiniLore.Modules.Users\InfiniLore.Modules.Users.csproj" />
    </ItemGroup>

</Project>
