<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AterraEngine.Unions" Version="6.1.0" />
    <PackageVersion Include="AterraEngine.Unions.Generators" Version="6.1.0" />
    <PackageVersion Include="CodeOfChaos.Ansi" Version="1.1.0" />
    <PackageVersion Include="CodeOfChaos.CliArgsParser" Version="5.1.2" />
    <PackageVersion Include="CodeOfChaos.CliArgsParser.Contracts" Version="5.1.2" />
    <PackageVersion Include="CodeOfChaos.CliArgsParser.Generators" Version="5.1.2" />
    <PackageVersion Include="CodeOfChaos.Extensions.DependencyInjection" Version="0.83.2" />
    <PackageVersion Include="CodeOfChaos.Extensions.DependencyInjection.Generators" Version="0.83.2" />
    <PackageVersion Include="CodeOfChaos.Extensions.EntityFrameworkCore" Version="0.83.2" />
    <PackageVersion Include="CodeOfChaos.Extensions.MicrosoftLogging" Version="0.83.2" />
    <PackageVersion Include="CodeOfChaos.Extensions.Serilog" Version="0.83.2" />
    <PackageVersion Include="CodeOfChaos.Types.UnitOfWork" Version="0.28.1" />
    <PackageVersion Include="FastEndpoints" Version="7.1.0" />
    <PackageVersion Include="FastEndpoints.Messaging.Core" Version="7.1.0" />
    <PackageVersion Include="FluentValidation" Version="12.1.0" />
    <PackageVersion Include="InfiniLore.InfiniBlazor" Version="0.1.0-preview.107" />
    <PackageVersion Include="InfiniLore.InfiniFrame" Version="0.1.0-preview.5" />
    <PackageVersion Include="InfiniLore.InfiniFrame.Blazor" Version="0.1.0-preview.5" />
    <PackageVersion Include="InfiniLore.InfiniFrame.Server" Version="0.1.0-preview.5" />
    <PackageVersion Include="Microsoft.CodeAnalysis" Version="4.14.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.10" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
    <PackageVersion Include="Serilog" Version="4.3.0" />
    <PackageVersion Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageVersion Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>
</Project>