<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>InfiniLore.Shared</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AterraEngine.Unions" />
        <PackageReference Include="AterraEngine.Unions.Generators" >
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
