<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
        <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CodeOfChaos.Extensions.MicrosoftLogging" />
        <PackageReference Include="InfiniLore.InfiniBlazor" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
        <PackageReference Include="Microsoft.Extensions.Http" />
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.Extensions.Logging" />
        <PackageReference Include="Serilog.Sinks.BrowserConsole" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\InfiniLore.Kiota.Extensions\InfiniLore.Kiota.Extensions.csproj" />
        <ProjectReference Include="..\InfiniLore.Kiota\InfiniLore.Kiota.csproj" />
        <ProjectReference Include="..\InfiniLore.Modules.Core.Shared.Components\InfiniLore.Modules.Core.Shared.Components.csproj" />
        <ProjectReference Include="..\InfiniLore.Modules.Core.Wasm\InfiniLore.Modules.Core.Wasm.csproj" />
        <ProjectReference Include="..\InfiniLore.Modules.LoreScopes.Shared.Components\InfiniLore.Modules.LoreScopes.Shared.Components.csproj" />
        <ProjectReference Include="..\InfiniLore.Modules.LoreScopes.Wasm\InfiniLore.Modules.LoreScopes.Wasm.csproj" />
        <ProjectReference Include="..\InfiniLore.Modules.LsMarkdownFiles.Shared.Components\InfiniLore.Modules.LsMarkdownFiles.Shared.Components.csproj" />
        <ProjectReference Include="..\InfiniLore.Modules.LsMarkdownFiles.Wasm\InfiniLore.Modules.LsMarkdownFiles.Wasm.csproj" />
    </ItemGroup>

    <ItemGroup>
        <_ContentIncludedByDefault Remove="Components\Library\MarkdownEditor.razor" />
    </ItemGroup>

</Project>
