<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CodeOfChaos.Extensions" />
        <PackageReference Include="CodeOfChaos.Extensions.AspNetCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory"/>
        <PackageReference Include="Testcontainers"/>
        <PackageReference Include="Testcontainers.MsSql"/>
        <PackageReference Include="Bogus"/>
        <PackageReference Include="JetBrains.Annotations"/>
        <PackageReference Include="TUnit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\InfiniLore.Server.Database\InfiniLore.Server.Database.csproj"/>
        <ProjectReference Include="..\DataSources.InfiniLore.Server\DataSources.InfiniLore.Server.csproj"/>
        <ProjectReference Include="..\Fakers.InfiniLore.Server\Fakers.InfiniLore.Server.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Configurations\"/>
        <Folder Include="Modules\Core\Messaging\" />
        <Folder Include="Modules\Core\Services\" />
    </ItemGroup>

</Project>
