// <auto-generated />
using System;
using InfiniLore.Server.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfiniLore.Server.Database.Migrations.Content
{
    [DbContext(typeof(ContentDb))]
    [Migration("20250527133749_HasAccessProtection")]
    partial class HasAccessProtection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InfiniLore.Server.Modules.Core.Database.AccessProtectionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModelOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProtectedModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SoftDeleteDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModelOwnerId");

                    b.HasIndex("ProtectedModelId")
                        .IsUnique();

                    b.ToTable("AccessProtectionModel");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("InfiniLore.Server.Modules.Core.Database.AccessProtectionRuleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccessProtectionModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("SoftDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccessProtectionModelId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.HasIndex("UserId", "Permission")
                        .IsUnique()
                        .HasDatabaseName("IX_UserId_Permission_Unique");

                    b.ToTable("AccessProtectionRuleModel");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("InfiniLore.Server.Modules.Core.Database.InfiniLoreUserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Auth0Github")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Auth0IdGoogle")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Auth0MailPassword")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SoftDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Auth0Github")
                        .IsUnique()
                        .HasFilter("[Auth0Github] IS NOT NULL");

                    b.HasIndex("Auth0IdGoogle")
                        .IsUnique()
                        .HasFilter("[Auth0IdGoogle] IS NOT NULL");

                    b.HasIndex("Auth0MailPassword")
                        .IsUnique()
                        .HasFilter("[Auth0MailPassword] IS NOT NULL");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("InfiniLoreUserModel");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("InfiniLore.Server.Modules.Core.Database.KeyValueEntryModel", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Value")
                        .HasMaxLength(2147483646)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("KeyValueEntryModel");
                });

            modelBuilder.Entity("InfiniLore.Server.Modules.LoreScopes.Database.LoreScopeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccessProtectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SoftDeleteDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccessProtectionId")
                        .IsUnique()
                        .HasFilter("[AccessProtectionId] IS NOT NULL");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "Name", "SoftDeleteDate")
                        .IsUnique()
                        .HasDatabaseName("IX_OwnerId_Name_Unique")
                        .HasFilter("[SoftDeleteDate] IS NOT NULL");

                    b.ToTable("LoreScopeModel");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("InfiniLore.Server.Modules.Core.Database.AccessProtectionModel", b =>
                {
                    b.HasOne("InfiniLore.Server.Modules.Core.Database.InfiniLoreUserModel", "ModelOwner")
                        .WithMany()
                        .HasForeignKey("ModelOwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ModelOwner");
                });

            modelBuilder.Entity("InfiniLore.Server.Modules.Core.Database.AccessProtectionRuleModel", b =>
                {
                    b.HasOne("InfiniLore.Server.Modules.Core.Database.AccessProtectionModel", null)
                        .WithMany("Rules")
                        .HasForeignKey("AccessProtectionModelId");

                    b.HasOne("InfiniLore.Server.Modules.Core.Database.AccessProtectionModel", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("InfiniLore.Server.Modules.LoreScopes.Database.LoreScopeModel", b =>
                {
                    b.HasOne("InfiniLore.Server.Modules.Core.Database.AccessProtectionModel", "AccessProtection")
                        .WithOne()
                        .HasForeignKey("InfiniLore.Server.Modules.LoreScopes.Database.LoreScopeModel", "AccessProtectionId");

                    b.HasOne("InfiniLore.Server.Modules.Core.Database.InfiniLoreUserModel", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessProtection");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("InfiniLore.Server.Modules.Core.Database.AccessProtectionModel", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
