// <auto-generated />
using System;
using InfiniLore.Server.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfiniLore.Server.Database.Migrations.Content
{
    [DbContext(typeof(ContentDb))]
    [Migration("20250224154428_AddUsername")]
    partial class AddUsername
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InfiniLore.Server.Database.Models.BasicData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SoftDeleteDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BasicData");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("InfiniLore.Server.Database.Models.Account.InfiniLoreUser", b =>
                {
                    b.HasBaseType("InfiniLore.Server.Database.Models.BasicData");

                    b.Property<string>("Auth0Github")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Auth0IdGoogle")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasIndex("Auth0Github")
                        .IsUnique()
                        .HasFilter("[Auth0Github] IS NOT NULL");

                    b.HasIndex("Auth0IdGoogle")
                        .IsUnique()
                        .HasFilter("[Auth0IdGoogle] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InfiniLore.Server.Database.Models.SystemData", b =>
                {
                    b.HasBaseType("InfiniLore.Server.Database.Models.BasicData");

                    b.ToTable("SystemData");
                });

            modelBuilder.Entity("InfiniLore.Server.Database.Models.UserData", b =>
                {
                    b.HasBaseType("InfiniLore.Server.Database.Models.BasicData");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("OwnerId");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("InfiniLore.Server.Database.Models.Data.System.KeyValueStore", b =>
                {
                    b.HasBaseType("InfiniLore.Server.Database.Models.SystemData");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Value")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.ToTable("KeyValueStores");
                });

            modelBuilder.Entity("InfiniLore.Server.Database.Models.SystemData", b =>
                {
                    b.HasOne("InfiniLore.Server.Database.Models.BasicData", null)
                        .WithOne()
                        .HasForeignKey("InfiniLore.Server.Database.Models.SystemData", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfiniLore.Server.Database.Models.UserData", b =>
                {
                    b.HasOne("InfiniLore.Server.Database.Models.BasicData", null)
                        .WithOne()
                        .HasForeignKey("InfiniLore.Server.Database.Models.UserData", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfiniLore.Server.Database.Models.Account.InfiniLoreUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("InfiniLore.Server.Database.Models.Data.System.KeyValueStore", b =>
                {
                    b.HasOne("InfiniLore.Server.Database.Models.SystemData", null)
                        .WithOne()
                        .HasForeignKey("InfiniLore.Server.Database.Models.Data.System.KeyValueStore", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
