// <auto-generated/>
#pragma warning disable CS0618
using InfiniLore.KiotaApiClient.Api.Account.Jwt.TokensCreate;
using InfiniLore.KiotaApiClient.Api.Account.Jwt.TokensRefresh;
using InfiniLore.KiotaApiClient.Api.Account.Jwt.TokensRevoke;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace InfiniLore.KiotaApiClient.Api.Account.Jwt
{
    /// <summary>
    /// Builds and executes requests for operations under \api\account\jwt
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class JwtRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The tokensCreate property</summary>
        public global::InfiniLore.KiotaApiClient.Api.Account.Jwt.TokensCreate.TokensCreateRequestBuilder TokensCreate
        {
            get => new global::InfiniLore.KiotaApiClient.Api.Account.Jwt.TokensCreate.TokensCreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tokensRefresh property</summary>
        public global::InfiniLore.KiotaApiClient.Api.Account.Jwt.TokensRefresh.TokensRefreshRequestBuilder TokensRefresh
        {
            get => new global::InfiniLore.KiotaApiClient.Api.Account.Jwt.TokensRefresh.TokensRefreshRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tokensRevoke property</summary>
        public global::InfiniLore.KiotaApiClient.Api.Account.Jwt.TokensRevoke.TokensRevokeRequestBuilder TokensRevoke
        {
            get => new global::InfiniLore.KiotaApiClient.Api.Account.Jwt.TokensRevoke.TokensRevokeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::InfiniLore.KiotaApiClient.Api.Account.Jwt.JwtRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public JwtRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/account/jwt", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::InfiniLore.KiotaApiClient.Api.Account.Jwt.JwtRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public JwtRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/account/jwt", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
