<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Messaging\NotificationHandlers\" />
      <Folder Include="Services\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FastEndpoints" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\InfiniLore.Server.Contracts\InfiniLore.Server.Contracts.csproj" />
      <ProjectReference Include="..\InfiniLore.Server.Modules.Core\InfiniLore.Server.Modules.Core.csproj" />
      <ProjectReference Include="..\InfiniLore.Shared\InfiniLore.Shared.csproj" />
    </ItemGroup>

</Project>
