// <auto-generated/>
#pragma warning disable CS0618
using InfiniLore.Kiota.Api.V1.DataUser.Item.Lorescope.Item;
using InfiniLore.Kiota.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace InfiniLore.Kiota.Api.V1.DataUser.Item.Lorescope
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\data-user\{userId}\lorescope
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LorescopeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the InfiniLore.Kiota.api.v1.dataUser.item.lorescope.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::InfiniLore.Kiota.Api.V1.DataUser.Item.Lorescope.Item.WithLoreScopeItemRequestBuilder"/></returns>
        public global::InfiniLore.Kiota.Api.V1.DataUser.Item.Lorescope.Item.WithLoreScopeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("loreScopeId", position);
                return new global::InfiniLore.Kiota.Api.V1.DataUser.Item.Lorescope.Item.WithLoreScopeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::InfiniLore.Kiota.Api.V1.DataUser.Item.Lorescope.LorescopeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LorescopeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/data-user/{userId}/lorescope?pageNumber={pageNumber}&reverse={reverse}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::InfiniLore.Kiota.Api.V1.DataUser.Item.Lorescope.LorescopeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LorescopeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/data-user/{userId}/lorescope?pageNumber={pageNumber}&reverse={reverse}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::InfiniLore.Kiota.Models.KiotaLoreScopesResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::InfiniLore.Kiota.Models.FastEndpointsProblemDetails">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::InfiniLore.Kiota.Models.KiotaLoreScopesResponse?> GetAsync(Action<RequestConfiguration<global::InfiniLore.Kiota.Api.V1.DataUser.Item.Lorescope.LorescopeRequestBuilder.LorescopeRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::InfiniLore.Kiota.Models.KiotaLoreScopesResponse> GetAsync(Action<RequestConfiguration<global::InfiniLore.Kiota.Api.V1.DataUser.Item.Lorescope.LorescopeRequestBuilder.LorescopeRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::InfiniLore.Kiota.Models.FastEndpointsProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::InfiniLore.Kiota.Models.KiotaLoreScopesResponse>(requestInfo, global::InfiniLore.Kiota.Models.KiotaLoreScopesResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="string"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::InfiniLore.Kiota.Models.FastEndpointsProblemDetails">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<string?> PostAsync(global::InfiniLore.Kiota.Models.KiotaCreateLorescopeEndpointRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<string> PostAsync(global::InfiniLore.Kiota.Models.KiotaCreateLorescopeEndpointRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::InfiniLore.Kiota.Models.FastEndpointsProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<string>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::InfiniLore.Kiota.Api.V1.DataUser.Item.Lorescope.LorescopeRequestBuilder.LorescopeRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::InfiniLore.Kiota.Api.V1.DataUser.Item.Lorescope.LorescopeRequestBuilder.LorescopeRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::InfiniLore.Kiota.Models.KiotaCreateLorescopeEndpointRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::InfiniLore.Kiota.Models.KiotaCreateLorescopeEndpointRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/api/v1/data-user/{userId}/lorescope", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::InfiniLore.Kiota.Api.V1.DataUser.Item.Lorescope.LorescopeRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::InfiniLore.Kiota.Api.V1.DataUser.Item.Lorescope.LorescopeRequestBuilder WithUrl(string rawUrl)
        {
            return new global::InfiniLore.Kiota.Api.V1.DataUser.Item.Lorescope.LorescopeRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class LorescopeRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("pageNumber")]
            public int? PageNumber { get; set; }
            [QueryParameter("reverse")]
            public bool? Reverse { get; set; }
        }
    }
}
#pragma warning restore CS0618
