<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
        <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CodeOfChaos.Extensions.MicrosoftLogging" Version="0.64.0" />
        <PackageReference Include="InfiniLore.InfiniBlazor" Version="0.1.0-preview.10" />
        <PackageReference Include="InfiniLore.InfiniBlazor.Contracts" Version="0.1.0-preview.10" />
        <PackageReference Include="InfiniLore.InfiniBlazor.Markdown" Version="0.1.0-preview.10" />
        <PackageReference Include="InfiniLore.InfiniBlazor.Theming" Version="0.1.0-preview.10" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.4"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.4"/>
        <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.4"/>
        <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.1"/>
        <PackageReference Include="Serilog.Sinks.BrowserConsole" Version="8.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\InfiniLore.Clients.Kiota.Extensions\InfiniLore.Clients.Kiota.Extensions.csproj"/>
        <ProjectReference Include="..\InfiniLore.Clients.Kiota\InfiniLore.Clients.Kiota.csproj"/>
        <ProjectReference Include="..\InfiniLore.Clients.Wasm.Services\InfiniLore.Clients.Wasm.Services.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Components\Library\MarkdownEditor.razor" />
    </ItemGroup>

</Project>
