<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection" Version="0.40.1" />
        <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection.Generators" Version="0.40.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="CodeOfChaos.Extensions" Version="0.40.1" />
        <PackageReference Include="CodeOfChaos.Extensions.Serilog" Version="0.40.1" />
        <PackageReference Include="CodeOfChaos.Types.DataSeeder" Version="0.21.0" />
        <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Old.InfiniLore.Contracts\Old.InfiniLore.Contracts.csproj" />
        <ProjectReference Include="..\Old.InfiniLore.Database\Old.InfiniLore.Database.csproj" />
        <ProjectReference Include="..\Old.InfiniLore.Server.Services\Old.InfiniLore.Server.Services.csproj" />
    </ItemGroup>

</Project>
