<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <RootNamespace>InfiniLore.Application.WebServer</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="wwwroot\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\core\InfiniLore.Core\InfiniLore.Core.csproj" />
      <ProjectReference Include="..\InfiniLore.Application\InfiniLore.Application.csproj" />
    </ItemGroup>


</Project>
