<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AterraEngine.Unions" Version="3.11.0" />
      <PackageReference Include="AterraEngine.Unions.Generators" Version="3.11.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="CodeOfChaos.Types.UnitOfWork.Contracts" Version="0.20.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\InfiniLore.Server.Database.Models\InfiniLore.Server.Database.Models.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Database\Repositories\Data\User\" />
    </ItemGroup>

</Project>
