<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AterraEngine.Unions" Version="4.1.0"/>
        <PackageReference Include="AterraEngine.Unions.Generators" Version="4.1.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection" Version="0.57.0" />
        <PackageReference Include="CodeOfChaos.Types.UnitOfWork.Contracts" Version="0.25.1"/>
        <PackageReference Include="InfiniLore.Credentials.Auth0.Contracts" Version="4.0.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\InfiniLore.Server.Database.Models\InfiniLore.Server.Database.Models.csproj"/>
    </ItemGroup>

</Project>
