// <auto-generated/>
#pragma warning disable CS0618
using InfiniLore.Kiota.Api.V1.Data.Project.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace InfiniLore.Kiota.Api.V1.Data.Project
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\data\project
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProjectRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the InfiniLore.Kiota.api.v1.data.project.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="WithLoreScopeItemRequestBuilder"/></returns>
        public global::InfiniLore.Kiota.Api.V1.Data.Project.Item.WithLoreScopeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("loreScopeId", position);
                return new global::InfiniLore.Kiota.Api.V1.Data.Project.Item.WithLoreScopeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="ProjectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/data/project", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="ProjectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/data/project", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
