<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\core\InfiniLore.Core.Database\InfiniLore.Core.Database.csproj" />
    <ProjectReference Include="..\..\src\modules\InfiniLore.Modules.Users.Shared\InfiniLore.Modules.Users.Shared.csproj" />
    <ProjectReference Include="..\..\src\modules\InfiniLore.Modules.Users\InfiniLore.Modules.Users.csproj" />
  </ItemGroup>
</Project>
