<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CodeOfChaos.Extensions" Version="0.59.1" />
        <PackageReference Include="CodeOfChaos.Extensions.AspNetCore" Version="0.59.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.4"/>
        <PackageReference Include="Testcontainers" Version="4.4.0"/>
        <PackageReference Include="Testcontainers.MsSql" Version="4.4.0"/>
        <PackageReference Include="Bogus" Version="35.6.3"/>
        <PackageReference Include="JetBrains.Annotations" Version="2024.3.0"/>
        <PackageReference Include="TUnit" Version="0.19.86" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\InfiniLore.Server.Database\InfiniLore.Server.Database.csproj"/>
        <ProjectReference Include="..\DataSources.InfiniLore.Server\DataSources.InfiniLore.Server.csproj"/>
        <ProjectReference Include="..\Fakers.InfiniLore.Server\Fakers.InfiniLore.Server.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Configurations\"/>
        <Folder Include="Repositories\Account\"/>
    </ItemGroup>

</Project>
