<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
        <RootNamespace>InfiniLore.Core</RootNamespace>
    </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>
</Project>
