<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Queries\Data\Discovery\"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
        <PackageReference Include="AterraEngine.Unions" Version="4.0.1" />
        <PackageReference Include="AterraEngine.Unions.Generators" Version="4.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <PackageReference Include="CodeOfChaos.Extensions" Version="0.43.0" />

        <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection.Generators" Version="0.43.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="CodeOfChaos.Extensions.MicrosoftLogging" Version="0.43.0" />
        <PackageReference Include="FluentValidation" Version="12.0.0-preview1"/>
        <PackageReference Include="InfiniLore.Credentials.Auth0.Contracts" Version="2.1.0-preview.3" />
        <PackageReference Include="MediatR" Version="12.4.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\InfiniLore.Server.Contracts\InfiniLore.Server.Contracts.csproj"/>
    </ItemGroup>

</Project>
