<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Commands\Data\System\"/>
        <Folder Include="Queries\Data\Discovery\"/>
        <Folder Include="Queries\Data\System\"/>
        <Folder Include="Queries\Data\User\"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="AterraEngine.Unions.Generators" Version="3.11.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        
        <PackageReference Include="CodeOfChaos.Extensions" Version="0.42.3" />
        <PackageReference Include="CodeOfChaos.Extensions.MicrosoftLogging" Version="0.42.3" />
        <PackageReference Include="FluentValidation" Version="12.0.0-preview1" />
        <PackageReference Include="MediatR" Version="12.4.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\InfiniLore.Server.Contracts\InfiniLore.Server.Contracts.csproj"/>
    </ItemGroup>

</Project>
