// <auto-generated/>
#pragma warning disable CS0618
using InfiniLore.Clients.Kiota.Api.V1.DataUser.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace InfiniLore.Clients.Kiota.Api.V1.DataUser
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\data-user
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DataUserRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the InfiniLore.Clients.Kiota.api.v1.dataUser.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="WithUserItemRequestBuilder"/></returns>
        public global::InfiniLore.Clients.Kiota.Api.V1.DataUser.Item.WithUserItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("userId", position);
                return new global::InfiniLore.Clients.Kiota.Api.V1.DataUser.Item.WithUserItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="DataUserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DataUserRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/data-user", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="DataUserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DataUserRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/data-user", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
