// <auto-generated/>
#pragma warning disable CS0618
using InfiniLore.KiotaApiClient.Api.Account.Identity.Create;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace InfiniLore.KiotaApiClient.Api.Account.Identity
{
    /// <summary>
    /// Builds and executes requests for operations under \api\account\identity
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IdentityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The create property</summary>
        public global::InfiniLore.KiotaApiClient.Api.Account.Identity.Create.CreateRequestBuilder Create
        {
            get => new global::InfiniLore.KiotaApiClient.Api.Account.Identity.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::InfiniLore.KiotaApiClient.Api.Account.Identity.IdentityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdentityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/account/identity", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::InfiniLore.KiotaApiClient.Api.Account.Identity.IdentityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdentityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/account/identity", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
