<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CodeOfChaos.Extensions.MicrosoftLogging" />
        <PackageReference Include="InfiniLore.InfiniBlazor" />
        <PackageReference Include="Microsoft.AspNetCore.Components" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\InfiniLore.Modules.Core.Shared.Contracts\InfiniLore.Modules.Core.Shared.Contracts.csproj" />
        <ProjectReference Include="..\InfiniLore.Modules.LsMarkdownFiles.Shared.Contracts\InfiniLore.Modules.LsMarkdownFiles.Shared.Contracts.csproj" />
        <ProjectReference Include="..\InfiniLore.Modules.LsMarkdownFiles.Wasm.Contracts\InfiniLore.Modules.LsMarkdownFiles.Wasm.Contracts.csproj" />
    </ItemGroup>

</Project>
