<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>

        <PackageReference Include="CodeOfChaos.Extensions" Version="0.53.0"/>
        <PackageReference Include="CodeOfChaos.Extensions.MicrosoftLogging" Version="0.53.0"/>
        <PackageReference Include="CodeOfChaos.Extensions.Serilog" Version="0.53.0"/>
        <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection.Generators" Version="0.53.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="MediatR" Version="12.4.1"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="9.0.3"/>
        <PackageReference Include="Microsoft.AspNetCore.Components" Version="9.0.3"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.3"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.3"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.3"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.3"/>
        <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.3"/>
        <PackageReference Include="Serilog" Version="4.2.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\InfiniLore.Server.Api\InfiniLore.Server.Api.csproj"/>
        <ProjectReference Include="..\InfiniLore.Server.Services.Auth0\InfiniLore.Server.Services.Auth0.csproj"/>
        <ProjectReference Include="..\InfiniLore.Server.Services.CQRS\InfiniLore.Server.Services.CQRS.csproj"/>
        <ProjectReference Include="..\InfiniLore.ServerClient.Contracts\InfiniLore.ServerClient.Contracts.csproj"/>
        <ProjectReference Include="..\InfiniLore.ServerClient.Shared\InfiniLore.ServerClient.Shared.csproj"/>
    </ItemGroup>

</Project>
