<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="Microsoft.AspNetCore.Components.Server">
        <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.12\Microsoft.AspNetCore.Components.Server.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="CodeOfChaos.Extensions" Version="0.39.3" />
      <PackageReference Include="CodeOfChaos.Extensions.MicrosoftLogging" Version="0.39.3" />
      <PackageReference Include="CodeOfChaos.Extensions.Serilog" Version="0.39.3" />
      <PackageReference Include="Microsoft.AspNetCore.Components" Version="9.0.2" />
      <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.2" />
      <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.2" />
      <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.2" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2" />
      <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.2" />
      <PackageReference Include="Serilog" Version="4.2.0" />
    </ItemGroup>

</Project>
