<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <RootNamespace>InfiniLore.ServerClient</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Shared\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AterraEngine.Unions" Version="4.1.0"/>
        <PackageReference Include="AterraEngine.Unions.Generators" Version="4.1.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\InfiniLore.Server.Api.Responses\InfiniLore.Server.Api.Responses.csproj"/>
    </ItemGroup>

</Project>
