// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Threading;
using CodeOfChaos.GeneratorTools;
using System.Collections.Immutable;
using System.Linq;

namespace InfiniLore.Server.MessageBroker.Generators;

// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
[Generator(LanguageNames.CSharp)]
public class MessageBrokerGenerator : IIncrementalGenerator {

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        IncrementalValueProvider<ImmutableArray<MessageDto>> data = context.SyntaxProvider
            .CreateSyntaxProvider(Predicate, Transform)
            .Where(static n => n is not null)
            .Collect()!;
        
        context.RegisterSourceOutput(context.CompilationProvider.Combine(data), GenerateSources);
    }

    private static bool Predicate(SyntaxNode node, CancellationToken _) 
        => node is ClassDeclarationSyntax or RecordDeclarationSyntax;

    private static MessageDto? Transform(GeneratorSyntaxContext ctx, CancellationToken _) {
        SemanticModel semanticModel = ctx.SemanticModel;
        
        INamedTypeSymbol? symbol = ctx.Node switch {
            ClassDeclarationSyntax classDeclaration => semanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol,
            RecordDeclarationSyntax recordDeclaration => semanticModel.GetDeclaredSymbol(recordDeclaration) as INamedTypeSymbol,
            _ => null
        };
        
        if (symbol is null) return null;
        if (symbol.IsAbstract) return null;
        
        return symbol.AllInterfaces.Any(x => x.IsDisplayName(TypeNames.ICommandBase) || x.IsDisplayName(TypeNames.IEvent)) 
            ? new MessageDto(symbol)
            : null;
    }
    
    private void GenerateSources(SourceProductionContext context, (Compilation Left, ImmutableArray<MessageDto> Right) tuple) {
        (Compilation _, ImmutableArray<MessageDto> data) = tuple;

        var builder = new GeneratorStringBuilder();
        builder.AppendAutoGenerated()
            .AppendUsings("FastEndpoints")
            .AppendNamespace("InfiniLore.Server.Modules.Core")
            .AppendNullableEnable()
            .AppendLine("public static partial class IMessageBrokerExtensions {")
            .ForEach(data, static (builder, dto) => builder.Indent(MessageDtoWriter.WriteBrokerExtension, dto))
            .AppendLine("}")
            .AppendNullableDisable();
        
        context.AddSource("IMessageBrokerExtensions.g.cs", builder.ToStringAndClear());
    }
}
