<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CodeOfChaos.Extensions.MicrosoftLogging" />
      <PackageReference Include="InfiniLore.InfiniBlazor" />
      <PackageReference Include="InfiniLore.InfiniBlazor.Markdown" />
      <PackageReference Include="InfiniLore.InfiniBlazor.Toasting" />
      <PackageReference Include="Microsoft.AspNetCore.Components" />
      <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\InfiniLore.Modules.Core.Shared.Contracts\InfiniLore.Modules.Core.Shared.Contracts.csproj" />
    </ItemGroup>

</Project>
