<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>a4a8b05e-7b66-43c1-9acb-32fdc9c6d05d</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Auth0.ManagementApi"/>
        <PackageReference Include="CodeOfChaos.CliArgsParser"/>
        <PackageReference Include="CodeOfChaos.CliArgsParser.Generators">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="InfiniLore.Credentials.Auth0" />
        <PackageReference Include="InfiniLore.Credentials.Auth0.Contracts" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
        <PackageReference Include="Serilog.Extensions.Hosting"/>
        <PackageReference Include="Serilog.Sinks.Console"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\InfiniLore.Shared\InfiniLore.Shared.csproj" />
    </ItemGroup>

</Project>
