<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>a4a8b05e-7b66-43c1-9acb-32fdc9c6d05d</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Auth0.ManagementApi" Version="7.36.0" />
        <PackageReference Include="CodeOfChaos.CliArgsParser" Version="4.9.0"/>
        <PackageReference Include="CodeOfChaos.CliArgsParser.Generators" Version="4.9.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="InfiniLore.Credentials.Auth0" Version="4.0.0"/>
        <PackageReference Include="InfiniLore.Credentials.Auth0.Contracts" Version="4.0.0"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
        <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0"/>
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\InfiniLore.ServerClient.Shared\InfiniLore.ServerClient.Shared.csproj"/>
    </ItemGroup>

</Project>
