// <auto-generated/>
#pragma warning disable CS0618
using InfiniLore.Clients.Kiota.Api.V1.Data.User.Item.Lorescope;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace InfiniLore.Clients.Kiota.Api.V1.Data.User.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\data\user\{userId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithUserItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The lorescope property</summary>
        public global::InfiniLore.Clients.Kiota.Api.V1.Data.User.Item.Lorescope.LorescopeRequestBuilder Lorescope
        {
            get => new global::InfiniLore.Clients.Kiota.Api.V1.Data.User.Item.Lorescope.LorescopeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::InfiniLore.Clients.Kiota.Api.V1.Data.User.Item.WithUserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/data/user/{userId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::InfiniLore.Clients.Kiota.Api.V1.Data.User.Item.WithUserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/data/user/{userId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
