<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>36e3e62b-26d0-4af0-b20e-8b5945483ab1</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\InfiniLore.Server.Api\InfiniLore.Server.Api.csproj"/>
        <ProjectReference Include="..\InfiniLore.Server.Database.Models\InfiniLore.Server.Database.Models.csproj"/>
        <ProjectReference Include="..\InfiniLore.Server.Database\InfiniLore.Server.Database.csproj"/>
        <ProjectReference Include="..\InfiniLore.Server.DataSeeder\InfiniLore.Server.DataSeeder.csproj"/>
        <ProjectReference Include="..\InfiniLore.Server.Services.Auth0\InfiniLore.Server.Services.Auth0.csproj"/>
        <ProjectReference Include="..\InfiniLore.Server.Services.CQRS\InfiniLore.Server.Services.CQRS.csproj"/>
        <ProjectReference Include="..\InfiniLore.Server.Services\InfiniLore.Server.Services.csproj"/>
        <ProjectReference Include="..\InfiniLore.Clients.Wasm\InfiniLore.Clients.Wasm.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AterraEngine.Unions" Version="4.0.1" />
        <PackageReference Include="Auth0.AspNetCore.Authentication" Version="1.4.1"/>
        <PackageReference Include="CodeOfChaos.Extensions.AspNetCore" Version="0.43.0" />
        <PackageReference Include="FastEndpoints" Version="5.35.0"/>
        <PackageReference Include="FastEndpoints.Swagger" Version="5.35.0"/>
        <PackageReference Include="InfiniLore.Credentials" Version="3.4.0" />
        <PackageReference Include="InfiniLore.Credentials.Auth0" Version="3.4.0" />
        <PackageReference Include="InfiniLore.Lucide" Version="0.13.477-preview.3" />
        <PackageReference Include="MediatR" Version="12.4.1"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.3" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.3" />
    </ItemGroup>

    <ItemGroup>
        <_ContentIncludedByDefault Remove="Components\Layout\MainLayout.razor"/>
        <_ContentIncludedByDefault Remove="Components\Layout\NavMenu.razor"/>
        <_ContentIncludedByDefault Remove="wwwroot\images\auth0-dotnet-ebook.png"/>
        <_ContentIncludedByDefault Remove="InfiniLore.Server\bin\Debug\net9.0\appsettings.Development.json"/>
        <_ContentIncludedByDefault Remove="InfiniLore.Server\bin\Debug\net9.0\appsettings.json"/>
        <_ContentIncludedByDefault Remove="InfiniLore.Server\bin\Debug\net9.0\BlazorDebugProxy\BrowserDebugHost.runtimeconfig.json"/>
        <_ContentIncludedByDefault Remove="InfiniLore.Server\bin\Debug\net9.0\InfiniLore.Clients.Wasm.staticwebassets.endpoints.json"/>
        <_ContentIncludedByDefault Remove="InfiniLore.Server\bin\Debug\net9.0\InfiniLore.Clients.Wasm.staticwebassets.runtime.json"/>
        <_ContentIncludedByDefault Remove="InfiniLore.Server\bin\Debug\net9.0\InfiniLore.Server.deps.json"/>
        <_ContentIncludedByDefault Remove="InfiniLore.Server\bin\Debug\net9.0\InfiniLore.Server.runtimeconfig.json"/>
        <_ContentIncludedByDefault Remove="InfiniLore.Server\bin\Debug\net9.0\InfiniLore.Server.staticwebassets.endpoints.json"/>
        <_ContentIncludedByDefault Remove="InfiniLore.Server\bin\Debug\net9.0\InfiniLore.Server.staticwebassets.runtime.json"/>
        <_ContentIncludedByDefault Remove="InfiniLore.Server\obj\Debug\net9.0\InfiniLore.Server.sourcelink.json"/>
        <_ContentIncludedByDefault Remove="InfiniLore.Server\obj\Debug\net9.0\staticwebassets.build.endpoints.json"/>
        <_ContentIncludedByDefault Remove="InfiniLore.Server\obj\Debug\net9.0\staticwebassets.build.json"/>
        <_ContentIncludedByDefault Remove="InfiniLore.Server\obj\Debug\net9.0\staticwebassets.development.json"/>
        <_ContentIncludedByDefault Remove="InfiniLore.Server\obj\Debug\net9.0\staticwebassets.pack.json"/>
        <_ContentIncludedByDefault Remove="InfiniLore.Server\obj\InfiniLore.Server.csproj.nuget.dgspec.json"/>
        <_ContentIncludedByDefault Remove="InfiniLore.Server\obj\project.assets.json"/>
        <_ContentIncludedByDefault Remove="InfiniLore.Server\obj\project.packagespec.json"/>
    </ItemGroup>

</Project>
