<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <LangVersion>latest</LangVersion>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CodeOfChaos.CliArgsParser.Library" Version="4.10.0" />
        <PackageReference Include="CodeOfChaos.CliArgsParser.Generators" Version="4.10.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="CodeOfChaos.Extensions" Version="0.64.0" />
        <PackageReference Include="Microsoft.Kiota.Http.HttpClientLibrary" Version="1.17.2"/>
        <PackageReference Include="JetBrains.Annotations" Version="2024.3.0"/>
        <PackageReference Include="LibGit2Sharp" Version="0.31.0"/>
        <PackageReference Include="NuGet.Protocol" Version="6.13.2"/>
        <PackageReference Include="TextCopy" Version="6.2.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\InfiniLore.Clients.Kiota\InfiniLore.Clients.Kiota.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Commands\"/>
    </ItemGroup>

</Project>
