<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <LangVersion>latest</LangVersion>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CodeOfChaos.CliArgsParser.Library" />
        <PackageReference Include="CodeOfChaos.CliArgsParser.Generators">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="CodeOfChaos.Extensions" />
        <PackageReference Include="CodeOfChaos.Extensions.Serilog" />
        <PackageReference Include="Microsoft.Extensions.Logging" />
        <PackageReference Include="Microsoft.Kiota.Http.HttpClientLibrary"/>
        <PackageReference Include="JetBrains.Annotations"/>
        <PackageReference Include="LibGit2Sharp"/>
        <PackageReference Include="NuGet.Protocol"/>
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.Extensions.Logging" />
        <PackageReference Include="TextCopy"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\InfiniLore.Kiota\InfiniLore.Kiota.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Commands\"/>
    </ItemGroup>

</Project>
