<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\InfiniLore.Modules.Core.Shared\InfiniLore.Modules.Core.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection" />
        <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection.Generators" >
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
