<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CodeOfChaos.Extensions.AspNetCore" />
        <PackageReference Include="Testcontainers.MsSql"/>
        <PackageReference Include="TUnit.Core" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\InfiniLore.Server.Database\InfiniLore.Server.Database.csproj"/>
        <ProjectReference Include="..\..\src\InfiniLore.Server.Modules.LoreScopes\InfiniLore.Server.Modules.LoreScopes.csproj" />
        <ProjectReference Include="..\..\src\InfiniLore.Server.Modules.MarkdownFiles\InfiniLore.Server.Modules.MarkdownFiles.csproj" />
        <ProjectReference Include="..\..\src\InfiniLore.Server.Modules.Users\InfiniLore.Server.Modules.Users.csproj" />
        <ProjectReference Include="..\Fakers.InfiniLore.Server\Fakers.InfiniLore.Server.csproj"/>
    </ItemGroup>

</Project>
