<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\core\InfiniLore.Core\InfiniLore.Core.csproj" />
      <ProjectReference Include="..\..\modules\InfiniLore.Modules.Assets\InfiniLore.Modules.Assets.csproj" />
      <ProjectReference Include="..\..\modules\InfiniLore.Modules.Projects\InfiniLore.Modules.Projects.csproj" />
      <ProjectReference Include="..\..\modules\InfiniLore.Modules.Users\InfiniLore.Modules.Users.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Sinks.Async" />
        <PackageReference Include="Serilog.Sinks.Console" />
        <PackageReference Include="CodeOfChaos.Extensions.Serilog" />
        <PackageReference Include="FastEndpoints.Swagger" />
        <PackageReference Include="InfiniLore.InfiniBlazor" />
    </ItemGroup>

</Project>
