<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>b66030d9-dd4d-418e-9b45-ed964bbc8e4e</UserSecretsId>
        
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AspNetCore.SwaggerUI.Themes" Version="2.0.0"/>
        <PackageReference Include="FastEndpoints" Version="5.32.0"/>
        <PackageReference Include="FastEndpoints.Attributes" Version="5.32.0"/>
        <PackageReference Include="FastEndpoints.Security" Version="5.32.0"/>
        <PackageReference Include="FastEndpoints.Swagger" Version="5.32.0"/>
        <PackageReference Include="JetBrains.Annotations" Version="2024.3.0"/>
        <PackageReference Include="MediatR" Version="12.4.1"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0"/>
        <PackageReference Include="Serilog" Version="4.2.0"/>
        <PackageReference Include="CodeOfChaos.Extensions.AspNetCore" Version="0.27.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0" PrivateAssets="All"/>
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0"/>
        <PackageReference Include="Testcontainers.MsSql" Version="4.1.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\client\InfiniLore.WasmClient\InfiniLore.WasmClient.csproj"/>
        <ProjectReference Include="..\InfiniLore.Database.Seeding\InfiniLore.Database.Seeding.csproj" />
        <ProjectReference Include="..\InfiniLore.Server.API\InfiniLore.Server.API.csproj"/>
        <ProjectReference Include="..\InfiniLore.Database.Repositories\InfiniLore.Database.Repositories.csproj"/>
        <ProjectReference Include="..\InfiniLore.Database.MsSqlServer\InfiniLore.Database.MsSqlServer.csproj"/>
        <ProjectReference Include="..\InfiniLore.Server.Services.Authentication\InfiniLore.Server.Services.Authentication.csproj"/>
        <ProjectReference Include="..\InfiniLore.Server.Services.Authorization\InfiniLore.Server.Services.Authorization.csproj"/>
        <ProjectReference Include="..\InfiniLore.Server.Services.CQRS.Handlers\InfiniLore.Server.Services.CQRS.Handlers.csproj"/>
        <ProjectReference Include="..\InfiniLore.Server.Services.CQRS.PipelineBehaviours\InfiniLore.Server.Services.CQRS.PipelineBehaviours.csproj" />
        <ProjectReference Include="..\InfiniLore.Server.Services\InfiniLore.Server.Services.csproj"/>
    </ItemGroup>

</Project>
