<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\InfiniLore.Kiota\InfiniLore.Kiota.csproj" />
      <ProjectReference Include="..\InfiniLore.Shared.Contracts\InfiniLore.Shared.Contracts.csproj" />
      <ProjectReference Include="..\InfiniLore.Shared\InfiniLore.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CodeOfChaos.Extensions.MicrosoftLogging"  />
      <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
      <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    </ItemGroup>

</Project>
