<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CodeOfChaos.Ansi" />
      <PackageReference Include="CodeOfChaos.CliArgsParser" />
      <PackageReference Include="CodeOfChaos.Extensions.Serilog" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
      <PackageReference Include="Serilog" />
      <PackageReference Include="Serilog.AspNetCore" />
      <PackageReference Include="Serilog.Sinks.Async" />
      <PackageReference Include="Serilog.Sinks.Console" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\core\InfiniLore.Core\InfiniLore.Core.csproj" />
      <ProjectReference Include="..\..\modules\InfiniLore.Modules.Assets\InfiniLore.Modules.Assets.csproj" />
      <ProjectReference Include="..\..\modules\InfiniLore.Modules.Projects\InfiniLore.Modules.Projects.csproj" />
      <ProjectReference Include="..\..\modules\InfiniLore.Modules.Users\InfiniLore.Modules.Users.csproj" />
    </ItemGroup>

</Project>
