<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
        <RootNamespace>InfiniLore.Core</RootNamespace>
    </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AterraEngine.Unions" />
    <PackageReference Include="AterraEngine.Unions.Generators">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
