<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FastEndpoints" Version="5.34.0" />
        <PackageReference Include="FastEndpoints.Attributes" Version="5.34.0" />
        <PackageReference Include="FastEndpoints.Generator" Version="5.34.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FastEndpoints.Security" Version="5.34.0" />
        <PackageReference Include="MediatR" Version="12.4.1"/>
        <PackageReference Include="Serilog" Version="4.2.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="Properties\launchSettings.json"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Old.InfiniLore.Database\Old.InfiniLore.Database.csproj" />
        <ProjectReference Include="..\Old.InfiniLore.Server.Services.CQRS.Requests\Old.InfiniLore.Server.Services.CQRS.Requests.csproj" />
        <ProjectReference Include="..\Old.InfiniLore.Server.Services\Old.InfiniLore.Server.Services.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Controllers\Admin\"/>
        <Folder Include="Controllers\Data\Discovery\"/>
        <Folder Include="Controllers\Data\System\"/>
        <Folder Include="Controllers\Data\User\Lorescopes\GetLorescopesUser\"/>
    </ItemGroup>

</Project>
