<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>

        <PackageReference Include="AterraEngine.Unions" Version="3.11.0" />
        <PackageReference Include="MediatR.Contracts" Version="2.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Old.InfiniLore.Contracts\Old.InfiniLore.Contracts.csproj" />
        <ProjectReference Include="..\Old.InfiniLore.Database.Models\Old.InfiniLore.Database.Models.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Commands\Data\Discovery\"/>
        <Folder Include="Commands\Data\System\"/>
        <Folder Include="Queries\Account\"/>
        <Folder Include="Queries\Data\Discovery\"/>
        <Folder Include="Queries\Data\System\"/>
    </ItemGroup>

</Project>
