<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CodeOfChaos.Extensions" Version="0.42.3" />
      <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection" Version="0.42.3" />
      <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection.Generators" Version="0.42.3">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="CodeOfChaos.Extensions.MicrosoftLogging" Version="0.42.3" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.2" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.2" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.Extensions.Identity.Core">
        <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\9.0.2\Microsoft.Extensions.Identity.Core.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
