<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>InfiniLore.Modules.LoreScopes.Wasm</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\InfiniLore.Kiota\InfiniLore.Kiota.csproj" />
      <ProjectReference Include="..\InfiniLore.Modules.LoreScopes.Shared.Contracts\InfiniLore.Modules.LoreScopes.Shared.Contracts.csproj" />
    </ItemGroup>

</Project>
