<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <PlatformTarget>x64</PlatformTarget>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <RootNamespace>InfiniLore.Application.Desktop</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="InfiniLore.InfiniFrame" />
      <PackageReference Include="InfiniLore.InfiniFrame.Blazor" />
      <PackageReference Include="Serilog" />
      <PackageReference Include="Serilog.AspNetCore" />
      <PackageReference Include="Serilog.Sinks.Async" />
      <PackageReference Include="Serilog.Sinks.Console" />
    </ItemGroup>

    <ItemGroup>
        <Content Update="wwwroot\**">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\InfiniLore.Core\InfiniLore.Core.csproj" />
    </ItemGroup>

</Project>
