<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
        <PackageReference Include="CodeOfChaos.Extensions" Version="0.51.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />
        <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="9.0.3" />
    </ItemGroup>

</Project>
