<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>


    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>


    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
        <PackageReference Include="CodeOfChaos.CliArgsParser" />
        <PackageReference Include="CodeOfChaos.CliArgsParser.Contracts" />
        <PackageReference Include="CodeOfChaos.CliArgsParser.Generators">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>


    <ItemGroup>
      <Folder Include="wwwroot\" />
    </ItemGroup>


    <ItemGroup>
      <ProjectReference Include="..\..\core\InfiniLore.Core.Components\InfiniLore.Core.Components.csproj" />
      <ProjectReference Include="..\..\core\InfiniLore.Core.Modular\InfiniLore.Core.Modular.csproj" />
      <ProjectReference Include="..\InfiniLore.Modules.Users.Shared\InfiniLore.Modules.Users.Shared.csproj" />
    </ItemGroup>

</Project>
