// <auto-generated/>
#pragma warning disable CS0618
using InfiniLore.Clients.Kiota.Api.V1.Account;
using InfiniLore.Clients.Kiota.Api.V1.DataUser;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace InfiniLore.Clients.Kiota.Api.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The account property</summary>
        public global::InfiniLore.Clients.Kiota.Api.V1.Account.AccountRequestBuilder Account
        {
            get => new global::InfiniLore.Clients.Kiota.Api.V1.Account.AccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dataUser property</summary>
        public global::InfiniLore.Clients.Kiota.Api.V1.DataUser.DataUserRequestBuilder DataUser
        {
            get => new global::InfiniLore.Clients.Kiota.Api.V1.DataUser.DataUserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
