// <auto-generated/>
#pragma warning disable CS0618
using InfiniLore.Kiota.Api.V1.DataLorescope.Item.MarkdownFile;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace InfiniLore.Kiota.Api.V1.DataLorescope.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\data-lorescope\{loreScopeId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithLoreScopeItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The markdownFile property</summary>
        public global::InfiniLore.Kiota.Api.V1.DataLorescope.Item.MarkdownFile.MarkdownFileRequestBuilder MarkdownFile
        {
            get => new global::InfiniLore.Kiota.Api.V1.DataLorescope.Item.MarkdownFile.MarkdownFileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::InfiniLore.Kiota.Api.V1.DataLorescope.Item.WithLoreScopeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLoreScopeItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/data-lorescope/{loreScopeId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::InfiniLore.Kiota.Api.V1.DataLorescope.Item.WithLoreScopeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLoreScopeItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/data-lorescope/{loreScopeId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
