// <auto-generated/>
#pragma warning disable CS0618
using InfiniLore.Clients.Kiota.Api.V1.Data.User;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace InfiniLore.Clients.Kiota.Api.V1.Data
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\data
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DataRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The user property</summary>
        public global::InfiniLore.Clients.Kiota.Api.V1.Data.User.UserRequestBuilder User
        {
            get => new global::InfiniLore.Clients.Kiota.Api.V1.Data.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::InfiniLore.Clients.Kiota.Api.V1.Data.DataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DataRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/data", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::InfiniLore.Clients.Kiota.Api.V1.Data.DataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DataRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/data", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
