<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
        <PackageReference Include="CodeOfChaos.Extensions.EntityFrameworkCore" />
        <PackageReference Include="CodeOfChaos.Extensions.MicrosoftLogging" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\InfiniLore.Core.Shared\InfiniLore.Core.Shared.csproj" />
    </ItemGroup>

</Project>
