<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>

        <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection" Version="0.57.0" />
        <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection.Generators" Version="0.57.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="CodeOfChaos.Extensions.MicrosoftLogging" Version="0.57.0" />
        <PackageReference Include="CodeOfChaos.Types.DataSeeder" Version="0.25.1"/>
        <PackageReference Include="CodeOfChaos.Types.UnitOfWork.Contracts" Version="0.25.1"/>
        <PackageReference Include="Microsoft.CodeAnalysis" Version="4.13.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.13.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.13.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.Scripting" Version="4.13.0" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.4" />
        <PackageReference Include="WolverineFx" Version="3.12.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\InfiniLore.Server.Database\InfiniLore.Server.Database.csproj"/>
        <ProjectReference Include="..\InfiniLore.Server.Services.Mediator\InfiniLore.Server.Services.Mediator.csproj"/>
    </ItemGroup>

</Project>
