<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>

        <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection" />
        <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection.Generators">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="CodeOfChaos.Extensions.MicrosoftLogging" />
        <PackageReference Include="CodeOfChaos.Types.DataSeeder"/>
        <PackageReference Include="CodeOfChaos.Types.UnitOfWork.Contracts"/>
        <PackageReference Include="Microsoft.CodeAnalysis"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting"/>
        <PackageReference Include="Microsoft.CodeAnalysis.Scripting"/>
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\InfiniLore.Server.Database\InfiniLore.Server.Database.csproj"/>
        <ProjectReference Include="..\InfiniLore.Server.Modules.Users.Contracts\InfiniLore.Server.Modules.Users.Contracts.csproj" />
        <ProjectReference Include="..\InfiniLore.Server.Modules.Users\InfiniLore.Server.Modules.Users.csproj" />
    </ItemGroup>

</Project>
