<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
        
        <!-- Main package name -->
        <PackageId>Old.InfiniLore.Contracts</PackageId>
        <Version>0.11.0</Version>
        <Authors>Anna Sas</Authors>
        <Description>A small library of commonly used types within the InfiniLore Server</Description>
        <PackageProjectUrl>https://github.com/InfiniLore/infinilore.cs</PackageProjectUrl>
        <PackageTags>infinilore</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <IncludeSymbols>true</IncludeSymbols>
        <DebugType>embedded</DebugType>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="AterraEngine.Unions" Version="3.11.0" />
        <PackageReference Include="AterraEngine.Unions.Generators" Version="3.11.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection" Version="0.36.4" />
        <PackageReference Include="CodeOfChaos.Types.UnitOfWork.Contracts" Version="0.18.1" />
        <PackageReference Include="FastEndpoints" Version="5.34.0" />
        <PackageReference Include="FastEndpoints.Attributes" Version="5.34.0" />
        <PackageReference Include="InfiniLore.Permissions" Version="1.6.1" />
        <PackageReference Include="MediatR.Contracts" Version="2.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.5.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Old.InfiniLore.Database.Models\Old.InfiniLore.Database.Models.csproj" />
        <ProjectReference Include="..\Old.InfiniLore.Server.Types\Old.InfiniLore.Server.Types.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="../../../LICENSE" Pack="true" PackagePath="" Visible="false" />
        <None Include="../../../README.md" Pack="true" PackagePath="" Visible="false" />
        <None Include="../../../assets/icon.png" Pack="true" PackagePath="" Visible="false" />
    </ItemGroup>

</Project>
