name: Run Unit Tests

on:
  pull_request:
    branches: [ core ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' 

    - name: Restore dependencies
      run: dotnet restore InfiniLore.sln

    - name: Build
      run: dotnet build InfiniLore.sln --configuration Release --no-restore

      
    - name: Run tests
      run: dotnet run -c Release --no-restore --no-build
      working-directory: "tests/Tests.InfiniLore.Server.Database"
