<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Messaging\Receivers\" />
      <Folder Include="Services\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\InfiniLore.Server.Database\InfiniLore.Server.Database.csproj" />
      <ProjectReference Include="..\InfiniLore.Server.Modules.Core\InfiniLore.Server.Modules.Core.csproj" />
      <ProjectReference Include="..\InfiniLore.Server.Modules.LoreScopes.Contracts\InfiniLore.Server.Modules.LoreScopes.Contracts.csproj" />
      <ProjectReference Include="..\InfiniLore.Server.Modules.Users.Contracts\InfiniLore.Server.Modules.Users.Contracts.csproj" />
    </ItemGroup>

</Project>
